service: omni-live-logistics-ready-for-billing

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
      Resource: "*"

package:
  individually: true

functions:
  Mcleod-ready-for-billing: ${file(config/functions/ready-for-billing.yml):function}

resources:
  Resources:
    ReadyforBilling: ${file(config/dynamo/ready-for-billing-table.yml):ready-for-billing}

custom:
  pythonRequirements:
    dockerizePip: true