function:
  name: omni-live-logistics-query-athena-${self:provider.stage}
  handler: src/query-Athena.lambda_handler
  description: omni live logistics copy s3 data
  timeout: 900
  tags:
    Name: query-athena 
  package:
    patterns:
      - "!**/*"
      - "src/shared/**"
      - "src/query-Athena.py"
      - "src/query_file.sql"
  runtime: python3.9
  layers:
      - arn:aws:lambda:us-east-1:332281781429:layer:pytz:1
  environment:
      ssm_parameter: !Ref MySSMParameter

